=== 0-Yorick-0/OpenClassRooms/OCR_XML/TPs/TP_doc1.dtd
<!-- Racine -->
<!ELEMENT repertoire (personne*)>

<!-- Personne -->
<!ELEMENT personne (nom, prenom, adresse, telephones, emails)>
<!ATTLIST personne sexe (masculin|feminin) #REQUIRED>

<!-- Nom et Prenom -->
<!ELEMENT nom (#PCDATA)>
<!ELEMENT prenom (#PCDATA)>

<!-- Bloc Adresse -->
<!ELEMENT adresse (numero, voie, codePostal, ville, pays)>
<!ELEMENT numero (#PCDATA)>

<!ELEMENT voie (#PCDATA)>
<!ATTLIST voie type CDATA #REQUIRED>

<!ELEMENT codePostal (#PCDATA)>
<!ELEMENT ville (#PCDATA)>
<!ELEMENT pays (#PCDATA)>

<!-- Telephones -->
<!ELEMENT telephones (telephone+)>

<!ENTITY telephone (#PCDATA)>
<!ENTITY % listeTel "type (fixe|portable|bureau) #REQUIRED">
<!ATTLIST telephone %listeTel;>

<!-- Emails -->
<!ELEMENT emails (email+)>

<!ELEMENT email (#PCDATA)>
<!ATTLIST email type (personnel|professionnel) #REQUIRED>

=== 0-Yorick-0/OpenClassRooms/OCR_XML/TPs/TP_Repertoire.xml
<?xml version="1.0" encodin="UTF-8" standalone="no" ?>

<!DOCTYPE repertoire SYSTEM "TP_doc1.dtd">

<repertoire>

  <personne sexe="masculin">
    <nom></nom>
    <prenom></prenom>
    <adresse>
      <numero></numero>
      <voie type="impasse"></voie>
      <codePostal></codePostal>
      <ville></ville>
      <pays></pays>
    </adresse>
    <telephones>
      <telephone type="fixe"></telephone>
      <telephone type="portable"></telephone>
    </telephone>
    <emails>
      <email type="personnel"></email>
      <email type="professionnel"></email>
    </emails>
  </personne>



</repertoire>
