=== 0-Yorick-0/OpenClassRooms/OCR_XML/Activite_Bibliotheque/bibli/bibliotheque.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<!-- balises isolées -->
  <!-- année seulement -->
  <xsd:element name="annee" type="xsd:gYear"/>

	<!-- balises titre -->
	<xsd:element name="titre">
    <xsd:complexType>

      <!-- attribut LANG -------------------------------------------- obligatoire -->
        <xsd:attribute name="lang" type="xsd:string" use="required"></xsd:attribute>

    </xsd:complexType>
  </xsd:element>
    	
  <!-- balise TITRES ------------------------------------- 1 à infinité de titres -->
  <xsd:element name="titres" >
    <xsd:complexType>

        <xsd:sequence>
            <xsd:element ref="titre" minOccurs="1" maxOccurs="unbounded"/>
        </xsd:sequence>

    </xsd:complexType>
  </xsd:element>
    	
  <!-- balise AUTEUR -------------- nom puis prenom optionnel, auteur obligatoire -->
  <xsd:element name="auteur" minOccurs="1" maxOccurs="1">
    <xsd:complexType>

      <xsd:sequence>
          <xsd:element name="nom" type="xsd:string"/>
          <xsd:element name="prenom" type="xsd:string" minOccurs="0"/>
      </xsd:sequence>

    </xsd:complexType>
  </xsd:element>
    	
  <!-- balise LIVRE --------------------------------------------------------------->
  <xsd:element name="livre">
    <xsd:complexType>

        <xsd:sequence>
            <xsd:element ref="titres"/>
            <xsd:element ref="auteur"/>
            <xsd:element ref="annee"/> 
        </xsd:sequence>
        
        <!-- attribut TYPE ----- optionnel et forcémment "poche"-->
        <xsd:attribute name="type" fixed="poche" use="optionnal"></xsd:attribute>

        <!-- attribut Style ------ obligatoire, liste prédéfinie-->
        <xsd:attribute name="style" use="required">
          <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="Policier"/>
                    <xsd:enumeration value="Théâtre"/>
                    <xsd:enumeration value="Fantastique"/>
                    <xsd:enumeration value="Bande Dessinée"/>
                    <xsd:enumeration value="Nouvelle"/>
                    <xsd:enumeration value="Biographie"/>
                    <xsd:enumeration value="Auto-Biographie"/>
                    <xsd:enumeration value="Documentaire"/>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>

    </xsd:complexType>
  </xsd:element>
    	
  <!-- balise bibliothèque --------------------------------------------------------->
  <xsd:element name="bibliotheque">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="livre"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
</xsd:schema>

=== 0-Yorick-0/OpenClassRooms/OCR_XML/Activite_Bibliotheque/bibli/bibli.xml
<bibliotheque xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="bibliotheque.xsd">
	<livre type="poche" style="Policier">
		<titres>
			<titre lang="en">The Templar Legacy</titre>
			<titre lang="fr">L'Héritage des Templiers</titre>
		</titres>
		<auteur>
			<nom>BERRY</nom>
			<prenom>Steve</prenom>
		</auteur>
		<annee>2006</annee>
	</livre>
	<livre style="Théâtre">
		<titres>
			<titre lang="fr">Le Tartuffe ou l'Imposteur</titre>
		</titres>
		<auteur>
			<nom>Molière</nom>
		</auteur>
		<annee>1664</annee>
	</livre>
	<livre type="poche" style="Fantastique">
		<titres>
			<titre lang="fr">Les Fourmis</titre>
			<titre lang="en">Empire of the Ants</titre>
		</titres>
		<auteur>
			<nom>WERBER</nom>
			<prenom>Bernard</prenom>
		</auteur>
		<annee>1991</annee>
	</livre>
	<livre style="Bande Dessinée">
		<titres>
			<titre lang="fr">Astérix et Latraviata</titre>
			<titre lang="en">Asterix and the Actress</titre>
			<titre lang="es">Astérix y Latraviata</titre>
			<titre lang="it">Asterix e Latraviata</titre>
		</titres>
		<auteur>
			<nom>UDERZO</nom>
			<prenom>Albert</prenom>
		</auteur>
		<annee>2001</annee>
	</livre>
</bibliotheque>
